import { useEffect, useState } from "react";
import { useDispatch, useSelector } from "react-redux";
import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import styles from "../styles/Home.module.css";
import { getNotes, deleteNote } from "../redux/actions/noteActions";
import {
  Typography,
  Card,
  CardActions,
  CardMedia,
  CardContent,
  AppBar,
  CssBaseline,
  Grid,
  Toolbar,
  Container,
  Button,
  ButtonGroup,
} from "@material-ui/core";
import { PhotoCamera } from "@mui/icons-material";
import AddNote from "../components/AddNote";

export default function Home() {
  const [open, setOpen] = useState(false);
  const handleClose = () => setOpen(false);
  const handleClickOpen = () => setOpen(true);
  const dispatch = useDispatch();
  useEffect(() => {
    dispatch(getNotes());
  }, [dispatch]);
  const { notes, loading, error } = useSelector((state) => state.noteList);
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Typography className={styles.title} variant="h2">
          Welcome to Notes App
        </Typography>
        <Button variant="outlined" color="primary" onClick={handleClickOpen}>
          Add Note
        </Button>
        <AddNote open={open} handleClose={handleClose} />
        <Grid container justifyContent="center" spacing={5}>
          {loading && <Typography variant="body1">Loading...</Typography>}
          {error && <Typography style={{ color: "red" }}>{error}</Typography>}
          {notes &&
            notes.map((note) => {
              return (
                <Grid item key={note._id}>
                  <Card elevation={10} variant="elevation">
                    <CardContent>
                      <Typography variant="h5">{note.title}</Typography>
                      <Typography variant="body2">
                        {note.description}
                      </Typography>
                    </CardContent>
                    <CardActions>
                      <Button variant="contained" color="primary">
                        Edit
                      </Button>
                      <Button
                        onClick={() => dispatch(deleteNote(note._id))}
                        variant="contained"
                        color="secondary"
                      >
                        Delete
                      </Button>
                    </CardActions>
                  </Card>
                </Grid>
              );
            })}
        </Grid>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}
